### ISSUE TITLE
Difficult to get a working config

### ISSUE THREAD

**Issue by softlion** [datalust/helm.datalust.co#46]
I'm sharing mine that finally work for ingestion.  
The ui was working out of the box, but It was quite difficult to understand how to setup the ingestion url/port, given that the nginx controller listens only on ports 80/443.

`Serilog config`
```cs
        .WriteTo.Seq("https://in.seq.yourdomain.eu", apiKey: "xxxxxxx")
```

To apply:
```shell
helm repo add datalust https://helm.datalust.co
helm repo update
helm upgrade seq datalust/seq -n yournamespace -f seq.yourdomain.helm.yaml --install --dry-run
```

`values.yaml`
```yaml
baseURI: https://seq.yourdomain.eu/

ingress:
  className: nginx
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  tls:
  - hosts:
    - seq.yourdomain.eu
    - in.seq.yourdomain.eu
    secretName: seq

persistence:
  size: 2Gi
  existingClaim: seq-yourdomain

ui:
  ingress:
    enabled: true
    path: /
    hosts:
      - seq.yourdomain.eu
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod

ingestion:
  ingress:
    #nginx controller only supports ports 80/443
    enabled: true
    path: /
    hosts:
      - in.seq.yourdomain.eu
    annotations:
      nginx.ingress.kubernetes.io/backend-protocol: "TCP"
      nginx.ingress.kubernetes.io/proxy-buffering: "on"
      nginx.ingress.kubernetes.io/proxy-buffer-size: "128k"
      nginx.ingress.kubernetes.io/proxy-buffers-number: "4"
```
