### ISSUE TITLE
Allow setting SEQ_FIRSTRUN_ADMINPASSWORD from Kubernetes secret

### ISSUE THREAD

**Issue by mloskot** [datalust/helm.datalust.co#64]
It would be useful if the chart supported injecting value for `firstRunAdminPassword` from Kubernetes `Secret`.

This would be useful for GitOps-managed Seq deployments, where `Secret`-s with passwords can be SOPS-encrypted or passwords can be imported into `Secret` resources from external key vaults e.g. using https://external-secrets.io

## Example

Here is a Helm chart with an interesting template 

https://github.com/gruntwork-io/helm-kubernetes-services/blob/099b7ceb735c60f799756ca8f8da2cb28bdc7ae1/charts/k8s-service/templates/_deployment_spec.tpl#L296-L306

which allows to specify this:

```yaml
spec:
  values:
    secrets:
      seq-administrator-password:
        as: environment
        items:
          password:
            envVarName: SEQ_FIRSTRUN_ADMINPASSWORD
```

where  `seq-administrator-password` is pre-existing Kubernetes secret in the same namespace where Seq will be deployed, with `password` data item.

I could try propose PR with such solution, if this of interest, I hope it is ;)

## References

This feature request is related to #54 but it is a much simpler plain Kubernetes suggestion.
